language: ruby
dist: trusty
before_script:
  # theses are dependencies of pandoc & pdfinfo
  - sudo apt-get install texlive texlive-xetex lmodern pandoc fonts-lato poppler-utils -y
script:
  - bundle exec jekyll build
  - pandoc pages/cgu.md -o _site/assets/cgu.pdf --latex-engine=xelatex
  # check pdf has at least one page
  - pdfinfo _site/assets/cgu.pdf | grep -w 'Pages:\s*[1-9].*'
